name: MLflow CI Training & Docker Build

on: [push]

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      # Ambil kode dari repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Siapkan Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 pandas scikit-learn numpy matplotlib seaborn dagshub

      # Jalankan MLflow Project
      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      # Upload Artefak MLflow ke GitHub Actions
      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: MLProject/mlruns

      # Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker Image dari Model MLflow
      - name: Build Docker Image with MLflow
        run: |
          cd MLProject
          RUN_ID=$(cat run_id.txt)
          echo "Building Docker image for Run ID: $RUN_ID"

          mlflow models build-docker \
            -m runs:/$RUN_ID/model \
            -n ${{ secrets.DOCKER_USERNAME }}/telco-churn-mlflow:latest

      # Push Image ke Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/telco-churn-mlflow:latest
